/* eslint-disable */
/**
 * Generated API module for Convex.
 *
 * THIS FILE IS AUTO-GENERATED by `npx convex dev`.
 * Run `npx convex dev` to regenerate with your actual API types.
 *
 * This stub allows TypeScript compilation before Convex is initialized.
 */
// @ts-nocheck
import type { AnyApi } from "convex/server";

// Placeholder api object -- will be fully typed after running `npx convex dev`
export const api: AnyApi = {} as AnyApi;
export const internal: AnyApi = {} as AnyApi;
