/* eslint-disable */
/**
 * Generated utilities for Convex server-side functions.
 *
 * THIS FILE IS AUTO-GENERATED by `npx convex dev`.
 * Run `npx convex dev` to regenerate with your actual schema types.
 *
 * These stubs allow TypeScript compilation before Convex is initialized.
 */
// @ts-nocheck
import {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
  internalQueryGeneric,
  internalMutationGeneric,
  internalActionGeneric,
} from "convex/server";
import type { DataModelFromSchemaDefinition } from "convex/server";
import schema from "../schema";

type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export const query = queryGeneric as typeof queryGeneric;
export const mutation = mutationGeneric as typeof mutationGeneric;
export const action = actionGeneric as typeof actionGeneric;
export const internalQuery = internalQueryGeneric as typeof internalQueryGeneric;
export const internalMutation = internalMutationGeneric as typeof internalMutationGeneric;
export const internalAction = internalActionGeneric as typeof internalActionGeneric;
